service: lambda-cognito-user-manager

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cognito-idp:ListUsers"
      Resource: "arn:aws:cognito-idp:*"

functions:
  cognito-manager:
    handler: handler.list_users
    memorySize: 128
    timeout: 30
